- hosts: all
  become: true
  tasks:
    - name: Create new deployment
      become: true
      become_user: server03
      command: kubectl apply -f /home/ubuntu/Deployment.yml
    - name: Create new service
      become: true
      become_user: server03
      command: kubectl apply -f /home/ubuntu/Service.yml
