apiVersion: v1
kind: Service
metadata:
  name: omnifood
  labels:
    app: omnifood
spec:
  selector:
    app: omnifood
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 31200
  type: NodePort
